#! /usr/bin/env Rscript
---
title: Figure-Manuscript- fine-mapping via SuSiE.
author: "Chief Ben-Eghan"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown
Load the required packages
```{r}
library(dplyr)
library(data.table)
library(ggplot2)
library(ggalluvial)
library(alluvial)
library(ggpubr)
library(grid)
library(reshape2)
library(grid)
library(devtools)
source_gist("524eade46135f6348140")
library(ggpmisc)
library(cowplot)
library(susieR)
```


```{r}
### load the LD matrix generated for 37-40Mb in EUR
chr17.matrix=fread("~/Desktop/OPEN/susie_mat/EURfolder/asthma6.ld")
chr17.matrix=as.matrix(chr17.matrix)


##load the EUR summary statistics file with Z-scores for each phenotype

EUR=fread('~/Desktop/OPEN/susie_mat/EURfolder/eur_chr17susie2ALL.txt')




### this genrates the model / phenotype in the EUR 

f1.b1=susie_rss(EUR$Z1, chr17.matrix, L=10)
f1.b2=susie_rss(EUR$Z2, chr17.matrix, L=10)
f1.e1=susie_rss(EUR$Z3, chr17.matrix, L=10)
f1.e2=susie_rss(EUR$Z4, chr17.matrix, L=10)
f1.l1=susie_rss(EUR$Z5, chr17.matrix, L=10)
f1.l2=susie_rss(EUR$Z6, chr17.matrix, L=10)
f1.m1=susie_rss(EUR$Z7, chr17.matrix, L=10)
f1.m2=susie_rss(EUR$Z8, chr17.matrix, L=10)
f1.n1=susie_rss(EUR$Z9, chr17.matrix, L=10)
f1.n2=susie_rss(EUR$Z10, chr17.matrix, L=10)
f1.w1=susie_rss(EUR$Z11, chr17.matrix, L=10)
f1.14=susie_rss(EUR$Z14, chr17.matrix, L=10)
f1.15=susie_rss(EUR$Z15, chr17.matrix, L=10)


susie_plot(f1.b1, y="PIP", add_legend = TRUE, main="BASO#")
cond1.b1$plot
s1.b1
susie_plot(f1.b2, y="PIP", add_legend = TRUE, main="BASO%")
cond1.b2$plot
s1.b2
susie_plot(f1.e1, y="PIP", add_legend = TRUE, main="EOS#")
cond1.e1$plot
s1.e1
susie_plot(f1.e2, y="PIP", add_legend = TRUE, main="EOS%")
cond1.e2$plot
s1.e2

susie_plot(f1.l1, y="PIP", add_legend = TRUE, main="LYM#")
cond1.l1$plot
s1.l1

susie_plot(f1.l2, y="PIP", add_legend = TRUE, main="LYM%")
cond1.l2$plot
s1.l2

susie_plot(f1.m1, y="PIP", add_legend = TRUE, main="MON#")
cond1.m1$plot
s1.m1

susie_plot(f1.m2, y="PIP", add_legend = TRUE, main="MON%")
cond1.m2$plot
s1.m2

susie_plot(f1.n1, y="PIP", add_legend = TRUE, main="NEU#")
cond1.n1$plot
s1.n1


susie_plot(f1.n2, y="PIP", add_legend = TRUE, main="NEU%")
cond1.n2$plot
s1.n2


susie_plot(f1.w1, y="PIP", add_legend = TRUE, main="WBC#")
cond1.w1$plot
s1.w1

susie_plot(f1.14, y="PIP", add_legend = TRUE, main="<18yrs")
cond1.18$plot
s1.14

susie_plot(f1.15, y="PIP", add_legend = TRUE, main="<40yrs")
cond1.40$plot
s1.15

### diagnostic check 

#s1.b1 = estimate_s_rss(EUR$Z1, chr17.matrix)
#s1.b2 = estimate_s_rss(EUR$Z2, chr17.matrix)
#s1.e1 = estimate_s_rss(EUR$Z3, chr17.matrix)
#s1.e2 = estimate_s_rss(EUR$Z4, chr17.matrix)
#s1.l1 = estimate_s_rss(EUR$Z5, chr17.matrix)
#s1.l2 = estimate_s_rss(EUR$Z6, chr17.matrix)
#s1.m1 = estimate_s_rss(EUR$Z7, chr17.matrix)
#s1.m2 = estimate_s_rss(EUR$Z8, chr17.matrix)
#s1.n1 = estimate_s_rss(EUR$Z9, chr17.matrix)
#s1.n2 = estimate_s_rss(EUR$Z10, chr17.matrix)
#s1.w1 = estimate_s_rss(EUR$Z11, chr17.matrix)
#s1.14 = estimate_s_rss(EUR$Z14, chr17.matrix)
#s1.15 = estimate_s_rss(EUR$Z15, chr17.matrix)





#cond1.b1 = kriging_rss(EUR$Z1, chr17.matrix)
cond1.b1$plot

#cond1.b2 = kriging_rss(EUR$Z2, chr17.matrix)
cond1.b2$plot


#cond1.e1 = kriging_rss(EUR$Z3, chr17.matrix)
cond1.e1$plot


#cond1.e2 = kriging_rss(EUR$Z4, chr17.matrix)
cond1.e2$plot

#cond1.l1 = kriging_rss(EUR$Z5, chr17.matrix)
cond1.l1$plot

#cond1.l2 = kriging_rss(EUR$Z6, chr17.matrix)
cond1.l2$plot

#cond1.m1 = kriging_rss(EUR$Z7, chr17.matrix)
cond1.m1$plot

#cond1.m2 = kriging_rss(EUR$Z8, chr17.matrix)
cond1.m2$plot

#cond1.n1 = kriging_rss(EUR$Z9, chr17.matrix)
cond1.n1$plot

#cond1.n2 = kriging_rss(EUR$Z10, chr17.matrix)
cond1.n2$plot

#cond1.w1 = kriging_rss(EUR$Z11, chr17.matrix)
cond1.w1$plot

#cond1.18 = kriging_rss(EUR$Z14, chr17.matrix)
cond1.18$plot

#cond1.40 = kriging_rss(EUR$Z15, chr17.matrix)
cond1.40$plot



######### load AFR matrix 






```
