#! /usr/bin/env Rscript
---
title: Figure-Manuscript- fine-mapping via SuSiE.
author: "Chief Ben-Eghan"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown
Load the required packages
```{r}
library(dplyr)
library(data.table)
library(ggplot2)
library(ggalluvial)
library(alluvial)
library(ggpubr)
library(grid)
library(reshape2)
library(grid)
library(devtools)
source_gist("524eade46135f6348140")
library(ggpmisc)
library(cowplot)
library(susieR)
```


```{r}
### load the LD matrix generated for 37-40Mb in EUR
chr17.matrix=fread("~/Desktop/OPEN/susie_mat/EURfolder/asthma6.ld")
chr17.matrix=as.matrix(chr17.matrix)


##load the EUR summary statistics file with Z-scores for each phenotype

EUR=fread('~/Desktop/OPEN/susie_mat/EURfolder/eur_chr17susie2ALL.txt')




### this genrates the susie model / phenotype in the EUR 

f1.b1=susie_rss(EUR$Z1, chr17.matrix, L=10)
f1.b2=susie_rss(EUR$Z2, chr17.matrix, L=10)
f1.e1=susie_rss(EUR$Z3, chr17.matrix, L=10)
f1.e2=susie_rss(EUR$Z4, chr17.matrix, L=10)
f1.l1=susie_rss(EUR$Z5, chr17.matrix, L=10)
f1.l2=susie_rss(EUR$Z6, chr17.matrix, L=10)
f1.m1=susie_rss(EUR$Z7, chr17.matrix, L=10)
f1.m2=susie_rss(EUR$Z8, chr17.matrix, L=10)
f1.n1=susie_rss(EUR$Z9, chr17.matrix, L=10)
f1.n2=susie_rss(EUR$Z10, chr17.matrix, L=10)
f1.w1=susie_rss(EUR$Z11, chr17.matrix, L=10)
f1.14=susie_rss(EUR$Z14, chr17.matrix, L=10)
f1.15=susie_rss(EUR$Z15, chr17.matrix, L=10)


## diagnostic check 
#check consistency between the z scores and LD matrix.A larger 𝑠 means there is a strong inconsistency between z scores and LD matrix.
#𝑠 is anumber between 0 and 1


#s1.b1 = estimate_s_rss(EUR$Z1, chr17.matrix)#baso#
#s1.b1
#[1] 1.25438e-05
#s1.b2 = estimate_s_rss(EUR$Z2, chr17.matrix)#baso%
#s1.b2
#[1] 9.212585e-06
#s1.e1 = estimate_s_rss(EUR$Z3, chr17.matrix)#eos#
#s1.e1
#[1] 0.0001021947
#s1.e2 = estimate_s_rss(EUR$Z4, chr17.matrix)#eos%
#s1.e2
#[1] 0.0001093257
#s1.l1 = estimate_s_rss(EUR$Z5, chr17.matrix)#lym#
#s1.l1
#[1] 2.933732e-05
#s1.l2 = estimate_s_rss(EUR$Z6, chr17.matrix)#lym%
#s1.l2
#[1] 3.802734e-05
#s1.m1 = estimate_s_rss(EUR$Z7, chr17.matrix)#mon#
#s1.m1
#[1] 1.25438e-05
#s1.m2 = estimate_s_rss(EUR$Z8, chr17.matrix)#mon%
#s1.m2
#[1] 7.471322e-05
#s1.n1 = estimate_s_rss(EUR$Z9, chr17.matrix)#neu#
#s1.n1
#[1] 0.0001389687
#s1.n2 = estimate_s_rss(EUR$Z10, chr17.matrix)#neu%
#[1] 5.439469e-05
#s1.w1 = estimate_s_rss(EUR$Z11, chr17.matrix)#wbc#
#s1.w1
#[1] 0.0001196477
#s1.14 = estimate_s_rss(EUR$Z14, chr17.matrix)#<18yrs
#s1.14
#[1] 0.0001355609
#s1.15 = estimate_s_rss(EUR$Z15, chr17.matrix) #<40yrs
#s1.15
#[1] 9.240556e-05
##s1.16
#s1.16 = estimate_s_rss(EUR$Z16, chr17.matrix) #asthma(age+sex)
#[1] 3.575471e-05




#The plot compares observed z score vs the expected value. The possible allele switched variants are labeled as red points 

cond1.b1 = kriging_rss(EUR$Z1, chr17.matrix) 
cond1.b1$plot#baso#

cond1.b2 = kriging_rss(EUR$Z2, chr17.matrix)
cond1.b2$plot#baso%

cond1.e1 = kriging_rss(EUR$Z3, chr17.matrix)
cond1.e1$plot#eos#

cond1.e2 = kriging_rss(EUR$Z4, chr17.matrix)
cond1.e2$plot#eos%

cond1.l1 = kriging_rss(EUR$Z5, chr17.matrix)
cond1.l1$plot#lym#

cond1.l2 = kriging_rss(EUR$Z6, chr17.matrix)
cond1.l2$plot#lym%

cond1.m1 = kriging_rss(EUR$Z7, chr17.matrix)
cond1.m1$plot#mon#

cond1.m2 = kriging_rss(EUR$Z8, chr17.matrix)
cond1.m2$plot#mon%

cond1.n1 = kriging_rss(EUR$Z9, chr17.matrix)
cond1.n1$plot#neu#

cond1.n2 = kriging_rss(EUR$Z10, chr17.matrix)
cond1.n2$plot#neu%

cond1.w1 = kriging_rss(EUR$Z11, chr17.matrix)
cond1.w1$plot#wbc#

cond1.18 = kriging_rss(EUR$Z14, chr17.matrix)
cond1.18$plot#<18yrs

cond1.40 = kriging_rss(EUR$Z15, chr17.matrix)
cond1.40$plot#<40yrs

cond1.16 = kriging_rss(EUR$Z16, chr17.matrix)
cond1.16$plot#asthma(age+sex)








susie_plot(f1.b1, y="PIP", add_legend = TRUE, main="BASO#")
cond1.b1$plot
s1.b1
susie_plot(f1.b2, y="PIP", add_legend = TRUE, main="BASO%")
cond1.b2$plot
s1.b2
susie_plot(f1.e1, y="PIP", add_legend = TRUE, main="EOS#")
cond1.e1$plot
s1.e1
susie_plot(f1.e2, y="PIP", add_legend = TRUE, main="EOS%")
cond1.e2$plot
s1.e2

susie_plot(f1.l1, y="PIP", add_legend = TRUE, main="LYM#")
cond1.l1$plot
s1.l1

susie_plot(f1.l2, y="PIP", add_legend = TRUE, main="LYM%")
cond1.l2$plot
s1.l2

susie_plot(f1.m1, y="PIP", add_legend = TRUE, main="MON#")
cond1.m1$plot
s1.m1

susie_plot(f1.m2, y="PIP", add_legend = TRUE, main="MON%")
cond1.m2$plot
s1.m2

susie_plot(f1.n1, y="PIP", add_legend = TRUE, main="NEU#")
cond1.n1$plot
s1.n1


susie_plot(f1.n2, y="PIP", add_legend = TRUE, main="NEU%")
cond1.n2$plot
s1.n2


susie_plot(f1.w1, y="PIP", add_legend = TRUE, main="WBC#")
cond1.w1$plot
s1.w1

susie_plot(f1.14, y="PIP", add_legend = TRUE, main="<18yrs")
cond1.18$plot
s1.14

susie_plot(f1.15, y="PIP", add_legend = TRUE, main="<40yrs")
cond1.40$plot
s1.15

susie_plot(f1.16, y="PIP", add_legend = TRUE, main="asthma(age+sex)")
cond1.16$plot
s1.16


#####plot 
pdf("~/Desktop/BASO#.pdf", 6,4)
susie_plot(f1.b1, y="PIP", add_legend = TRUE, main="BASO#")
cond1.b1$plot
dev.off()

pdf("~/Desktop/BASO_perc.pdf", 6,4)
susie_plot(f1.b2, y="PIP", add_legend = TRUE, main="BASO%")
cond1.b2$plot
dev.off()

pdf("~/Desktop/EOS#.pdf", 6,4)
susie_plot(f1.e1, y="PIP", add_legend = TRUE, main="EOS#")
cond1.e1$plot
dev.off()

pdf("~/Desktop/EOS_perc.pdf", 6,4)
susie_plot(f1.e2, y="PIP", add_legend = TRUE, main="EOS%")
cond1.e2$plot
dev.off()

pdf("~/Desktop/LYM#.pdf", 6,4)
susie_plot(f1.l1, y="PIP", add_legend = TRUE, main="LYM#")
cond1.l1$plot
dev.off()

pdf("~/Desktop/LYM_perc.pdf", 6,4)
susie_plot(f1.l2, y="PIP", add_legend = TRUE, main="LYM%")
cond1.l2$plot
dev.off()

pdf("~/Desktop/MON#.pdf", 6,4)
susie_plot(f1.m1, y="PIP", add_legend = TRUE, main="MON#")
cond1.m1$plot
dev.off()

pdf("~/Desktop/MON_perc.pdf", 6,4)
susie_plot(f1.m2, y="PIP", add_legend = TRUE, main="MON%")
cond1.m2$plot
dev.off()

pdf("~/Desktop/NEU#.pdf", 6,4)
susie_plot(f1.n1, y="PIP", add_legend = TRUE, main="NEU#")
cond1.n1$plot
dev.off()

pdf("~/Desktop/NEU_perc.pdf", 6,4)
susie_plot(f1.n2, y="PIP", add_legend = TRUE, main="NEU%")
cond1.n2$plot
dev.off()

pdf("~/Desktop/WBC#.pdf", 6,4)
susie_plot(f1.w1, y="PIP", add_legend = TRUE, main="WBC#")
cond1.w1$plot
dev.off()

pdf("~/Desktop/<18yrs.pdf", 6,4)
susie_plot(f1.14, y="PIP", add_legend = TRUE, main="<18yrs")
cond1.18$plot
dev.off()

pdf("~/Desktop/<40yrs.pdf", 6,4)
susie_plot(f1.15, y="PIP", add_legend = TRUE, main="<40yrs")
cond1.40$plot
dev.off()

pdf("~/Desktop/asthma_age_sex.pdf", 6,4)
susie_plot(f1.16, y="PIP", add_legend = TRUE, main="asthma(age+sex)")
cond1.16$plot
dev.off()




######### load SAS matrix 

SAS.ld=fread("/Users/chiefeghan/Desktop/OPEN/susie_mat/SASfolder/SAS.ld")
SAS.ld=as.matrix(SAS.ld)

#
SAS.susie=fread("/Users/chiefeghan/Desktop/OPEN/susie_mat/SASfolder/SAS.Susie.summary.95.txt")
SAS.snps=fread("~/Desktop/OPEN/susie_mat/SASfolder/SAS.z")


##NEU
SAS.snps$BETA.9=SAS.susie[match(SAS.snps$position, SAS.susie$position), "BETA9"]
SAS.snps$SE.9=SAS.susie[match(SAS.snps$position, SAS.susie$position), "SE9"]
SAS.snps$P.9=SAS.susie[match(SAS.snps$position, SAS.susie$position), "P9"]
SAS.snps$Z.9=SAS.susie[match(SAS.snps$position, SAS.susie$position), "Z9.x"]

s1.n1.sas=estimate_s_rss(SAS.snps$Z.9, SAS.ld)
s1.n1.sas
#[1] 1.434076e-06

##WBC 
SAS.snps$BETA.11=SAS.susie[match(SAS.snps$position, SAS.susie$position), "BETA11"]
SAS.snps$SE.11=SAS.susie[match(SAS.snps$position, SAS.susie$position), "SE11"]
SAS.snps$P.11=SAS.susie[match(SAS.snps$position, SAS.susie$position), "P11"]
SAS.snps$Z.11=SAS.susie[match(SAS.snps$position, SAS.susie$position), "Z11.x"]

s1.w1.sas=estimate_s_rss(SAS.snps$Z.11, SAS.ld)
s1.w1.sas
#[1] 1.592856e-06

# diagnostic plot 
cond1.sas.n1 = kriging_rss(SAS.snps$Z.9, SAS.ld)
cond1.sas.w1 = kriging_rss(SAS.snps$Z.11, SAS.ld)


###

pdf("~/Desktop/SAS.NEU#.pdf", 6,4)
susie_plot(f1.sas.n1, y="PIP", add_legend = TRUE, main="SAS.NEU#")
cond1.sas.n1$plot
dev.off()

pdf("~/Desktop/SAS.WBC#.pdf", 6,4)
susie_plot(f1.sas.w1, y="PIP", add_legend = TRUE, main="SAS.WBC#")
cond1.sas.w1$plot
dev.off()



###load AFR 



```
